name: Deploy to Firebase Hosting on test branch
'on':
  push:
    branches:
      - test
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean npm cache and remove lock file
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json
      - name: Install Dependencies
        run: npm install
      - run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: tasktrees-fb.web.app
          VITE_DATABASE_URL: ${{ secrets.VITE_DATABASE_URL }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGE_SENDER_ID: ${{ secrets.VITE_MESSAGE_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKTREES_FB }}'
          channelId: live
          projectId: tasktrees-fb
